### ISSUE TITLE
Crashes on launch with NullPointerException

### ISSUE THREAD

**Issue by ghost** [sikuli/sikuli#4]
***\* Known Problem (https://answers.launchpad.net/sikuli/+faq/1766)

***\* Pls. report issues, bugs and questions at https://launchpad.net/sikuli

---

Mac OS X 10.6, Snow Leopard.

If you close the application with a .sikuli file already open then try to launch Sikuli IDE again, you will get an error dialog:

**Cannot launch Java application**
Uncaught exception in main method: java.lang.NullPointerException

The application will not quit normally and must be killed with the Force Quit command.

Sikuli IDE can only be started again by overwriting the IDE_SESSION key from the preferences file before launching.

`defaults write org.sikuli.ide '/org/sikuli/ide/' -dict-add "IDE_SESSION" -string ';'`

**Comment by ghost** [comment]
This issue is specific to the script I was working on. This line was the culprit:

``` python
type("image.png")
```

This confused the IDE. It thought that this code meant there was a screenshot with the file name "image.png" in the .sikuli directory. There was not. This was just a string I was telling Sikuli to type into a dialog box.

Changing the code to

``` python
type("image%spng" % ".")
```

fixed things.

**Comment by RaiMan** [comment]
Thanks. I will add your workarounds to the relevant FAQ on launchpad.

**Comment by RaiMan** [comment]
just had a look and tested:

the issue is solved in latest build r931.

see: https://bugs.launchpad.net/sikuli/+bug/879955

**Comment by dound** [comment]
Cool @ fixed in r931.  Looks like r905 is available in the downloads section.  Can't wait for the fix :).

**Comment by mitchm101** [comment]
I am still seeing this issue with build 905.  If I delete ~/Library/Preferences/org.sikuli.ide.plist and the lock file, I an open the IDE

**Comment by RaiMan** [comment]
I am using r931 on my Mac: works in both cases:
- script last opened no longer exists
- image in code not found in bundle

**Comment by mitchm101** [comment]
Ok, thanks.  I misread the post and thought it was fixed in 905
